"use server";

import { prisma } from "@/prisma";
import { UserModel } from "@/types";
import { User } from "@prisma/client";

export default async function FeedToDB({
  email,
  name,
  age,
  occupation,
}: UserModel) {
  try {
    const newUser: User = await prisma.user.create({
      data: {
        email: email,
        name: name,
        age: age,
        occupation: occupation,
        // Assuming "id" is autogenerated by the database, you don't need to set it manually
      },
    });

    // Optionally, you might want to return the created user or any other value
    return newUser;
  } catch (error) {
    console.error("Error creating user:", error);
    throw error; // Rethrow the error if needed
  } finally {
    // Optionally, you can close the Prisma connection here if needed
    await prisma.$disconnect();
  }
}
